name: crisiscleanup-3-awsconnect

service: crisiscleanup-3-awsconnect
app: crisiscleanup-3-awsconnect
org: crisiscleanup

package:
  individually: true

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  websocketsApiName: crisiscleanup-3-awsconnect-ws
  websocketsApiRouteSelectionExpression: $request.body.action
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource:
        - 'Fn::Join':
            - ':'
            - - 'arn:aws:lambda'
              - Ref: 'AWS::Region'
              - Ref: 'AWS::AccountId'
              - 'function:${self:service}-${self:custom.stage}-awsConnect'
    - Effect: 'Allow'
      Action:
        - 'dynamodb:Query'
        - 'dynamodb:Scan'
        - 'dynamodb:UpdateItem'
        - 'dynamodb:DeleteItem'
        - 'dynamodb:PutItem'
        - 'dynamodb:GetItem'
        - 'dynamodb:BatchGetItem'
      Resource:
        - 'Fn::Join':
            - ':'
            - - 'arn:aws:dynamodb'
              - Ref: 'AWS::Region'
              - Ref: 'AWS::AccountId'
              - 'table/connect-*'
plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-plugin-warmup
  - serverless-dotenv-plugin
  - serverless-prune-plugin
  - serverless-dynamodb-local

custom:
  stage: ${opt:stage, self:provider.stage}
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
    packager: 'yarn'
  warmup:
    enabled: false
    events:
      - schedule: rate(5 minutes)
    prewarm: true
    concurrency: 1
  prune:
    automatic: true
    number: 5
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migration: true

functions:
  awsConnect:
    handler: src/index.default

  connectionHandler:
    handler: src/index.wsConnectionHandler
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect

  defaultHandler:
    handler: src/index.wsHandler
    events:
      - websocket:
          route: handler

resources:
  Resources:
    # Connect Metrics Table
    metricsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: connect-metrics-table
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: type
            AttributeType: S
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: type
            KeyType: HASH
          - AttributeName: name
            KeyType: RANGE
    agentsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: connect-agents-table
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: agent_id
            AttributeType: S
          - AttributeName: state
            AttributeType: S
          - AttributeName: current_contact_id
            AttributeType: S
        KeySchema:
          - AttributeName: agent_id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: state-index
            KeySchema:
              - AttributeName: state
                KeyType: HASH
              - AttributeName: agent_id
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
          - IndexName: contact-index
            KeySchema:
              - AttributeName: current_contact_id
                KeyType: HASH
            Projection:
              ProjectionType: ALL
