name: crisiscleanup-3-awsconnect

service: crisiscleanup-3-awsconnect
app: crisiscleanup-3-awsconnect
org: crisiscleanup

awsConnectPda:
  component: "@serverless/aws-lambda"
  inputs:
    name: crisiscleanup-3-awsconnect
    description: CC3 AWS Connect Lambda Integrations
    memory: 128
    timeout: 20
    code: ./src
    handler: index.handler
    runtime: nodejs12.x
    region: us-east-1
    bucket: crisiscleanup-3-awsconnect
    env:
      CC_AUTH_TOKEN: ${env.CC_AUTH_TOKEN}
