name: crisiscleanup-3-awsconnect

service: crisiscleanup-3-awsconnect
app: crisiscleanup-3-awsconnect
org: crisiscleanup

awsConnect:
  component: "@serverless/aws-lambda"
  inputs:
    name: crisiscleanup-3-awsconnect
    description: CC3 AWS Connect Lambda Integrations
    memory: 128
    timeout: 20
    code: ./src
    handler: index.handler
    runtime: nodejs12.x
    region: us-east-1
    bucket: crisiscleanup-3-awsconnect
    env:
      CC_AUTH_TOKEN: ${env.CC_AUTH_TOKEN}
      CC_API_BASE_URL: ${env.CC_API_BASE_URL}
      CC_DEV_AUTH_TOKEN: ${env.CC_DEV_AUTH_TOKEN}
      CC_DEV_API_BASE_URL: ${env.CC_DEV_API_BASE_URL}

metricsTable:
  component: "@serverless/aws-dynamodb"
  app: crisiscleanup-3-awsconnect
  org: crisiscleanup
  name: connect-metrics-table

  inputs:
    name: connect-metrics-table
    region: us-east-1
    attributeDefinitions:
      - AttributeName: type
        AttributeType: S
      - AttributeName: name
        AttributeType: S
    keySchema:
      - AttributeName: type
        KeyType: HASH
      - AttributeName: name
        KeyType: RANGE
