name: crisiscleanup-3-awsconnect

service: crisiscleanup-3-awsconnect
app: crisiscleanup-3-awsconnect
org: crisiscleanup

package:
  individually: true

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  timeout: 10
  logRetentionInDays: 14
  logs:
    websocket:
      level: INFO
  tracing:
    apiGateway: true
    lambda: true
  websocketsApiName: crisiscleanup-3-awsconnect-ws
  websocketsApiRouteSelectionExpression: $request.body.action
  iamManagedPolicies:
    - ${cf:serverless-domain-manager-awsconnect.ServerlessDomainManagerDeployPolicyArn}
    - arn:aws:iam::aws:policy/service-role/AWSLambdaRole
    - arn:aws:iam::aws:policy/AmazonAPIGatewayInvokeFullAccess
    - arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
    - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
    - arn:aws:iam::aws:policy/AmazonSNSFullAccess

  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource:
        - 'Fn::Join':
            - ':'
            - - 'arn:aws:lambda'
              - Ref: 'AWS::Region'
              - Ref: 'AWS::AccountId'
              - 'function:${self:service}-${self:custom.stage}-*'
    - Effect: 'Allow'
      Action:
        - 'execute-api:*'
      Resource:
        - 'Fn::Join':
            - ':'
            - - 'arn:aws:execute-api'
              - Ref: 'AWS::Region'
              - Ref: 'AWS::AccountId'
              - '*'
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource:
        - 'Fn::Join':
            - ':'
            - - 'arn:aws:logs'
              - Ref: 'AWS::Region'
              - Ref: 'AWS::AccountId'
              - 'log-group:/aws/lambda/*:*:*'
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource:
        - 'Fn::Join':
            - ':'
            - - 'arn:aws:logs'
              - Ref: 'AWS::Region'
              - Ref: 'AWS::AccountId'
              - 'log-group:/aws/websocket/*:*:*'
    - Effect: 'Allow'
      Action:
        - 'dynamodb:Query'
        - 'dynamodb:Scan'
        - 'dynamodb:UpdateItem'
        - 'dynamodb:DeleteItem'
        - 'dynamodb:PutItem'
        - 'dynamodb:GetItem'
        - 'dynamodb:BatchGetItem'
      Resource:
        - 'Fn::Join':
            - ':'
            - - 'arn:aws:dynamodb'
              - Ref: 'AWS::Region'
              - Ref: 'AWS::AccountId'
              - 'table/connect-*'
plugins:
  - serverless-webpack
  - serverless-plugin-warmup
  - serverless-dotenv-plugin
  - serverless-prune-plugin
  - serverless-dynamodb-local
  - serverless-domain-manager
  - serverless-stack-output
  - serverless-sentry
  - serverless-offline

custom:
  stage: ${opt:stage, self:provider.stage}
  dynamic: ${file(config.js)}
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
    packager: 'yarn'
  sentry:
    dsn: https://3f546c2c910b47dba24e1dcf2dfdc544@o317954.ingest.sentry.io/5213073
  warmup:
    enabled:
      - staging
      - prod
    events:
      # Run WarmUp every 5 minutes Mon-Fri between 8:00am and 5:55pm (UTC)
      - schedule: 'cron(0/5 8-17 ? * MON-FRI *)'
    prewarm: true
    concurrency: 1
  prune:
    automatic: true
    number: 5
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migration: true
  customDomain: ${self:custom.dynamic.domain}
  output:
    file: .build/stack.yml

functions:
  awsConnect:
    provisionedConcurrency: 3
    reservedConcurrency: 5
    handler: src/index.default
    onError: !Ref ConnectErrorsTopic

  connectionHandler:
    handler: src/index.wsConnectionHandler
    provisionedConcurrency: 3
    reservedConcurrency: 5
    memorySize: 512
    onError: !Ref ConnectErrorsTopic
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect

  wsHandler:
    provisionedConcurrency: 3
    reservedConcurrency: 5
    handler: src/index.wsHandler
    onError: !Ref ConnectErrorsTopic
    events:
      - websocket: $default

  metricStreamHandler:
    provisionedConcurrency: 3
    reservedConcurrency: 5
    handler: src/index.metricStreamHandler
    onError: !Ref ConnectErrorsTopic

  contactStreamHandler:
    provisionedConcurrency: 3
    reservedConcurrency: 5
    handler: src/index.contactStreamHandler
    onError: !Ref ConnectErrorsTopic

  agentStreamHandler:
    provisionedConcurrency: 3
    reservedConcurrency: 5
    handler: src/index.agentStreamHandler
    onError: !Ref ConnectErrorsTopic

resources:
  Resources:
    # Connect Metrics Table
    metricsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: connect-metrics-table-${self:custom.stage}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: type
            AttributeType: S
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: type
            KeyType: HASH
          - AttributeName: name
            KeyType: RANGE
        StreamSpecification:
          StreamViewType: NEW_IMAGE
    agentsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: connect-agents-table-${self:custom.stage}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: agent_id
            AttributeType: S
          - AttributeName: state
            AttributeType: S
          - AttributeName: current_contact_id
            AttributeType: S
          - AttributeName: active
            AttributeType: S
        KeySchema:
          - AttributeName: agent_id
            KeyType: HASH
        StreamSpecification:
          StreamViewType: NEW_IMAGE
        GlobalSecondaryIndexes:
          - IndexName: state-index
            KeySchema:
              - AttributeName: active
                KeyType: HASH
              - AttributeName: state
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
          - IndexName: contact-index
            KeySchema:
              - AttributeName: current_contact_id
                KeyType: HASH
            Projection:
              ProjectionType: ALL
    contactsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: connect-contacts-table-${self:custom.stage}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: contact_id
            AttributeType: S
          - AttributeName: state
            AttributeType: S
        KeySchema:
          - AttributeName: contact_id
            KeyType: HASH
        StreamSpecification:
          StreamViewType: NEW_IMAGE
        GlobalSecondaryIndexes:
          - IndexName: state-index
            KeySchema:
              - AttributeName: state
                KeyType: HASH
              - AttributeName: contact_id
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true
    clientsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: connect-clients-table-${self:custom.stage}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: connection_id
            AttributeType: S
          - AttributeName: client_type
            AttributeType: S
          - AttributeName: user_id
            AttributeType: S
        KeySchema:
          - AttributeName: user_id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: type-index
            KeySchema:
              - AttributeName: client_type
                KeyType: HASH
              - AttributeName: connection_id
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
          - IndexName: connection-index
            KeySchema:
              - AttributeName: connection_id
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true

    ConnectErrorsTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: AWSConnectErrorTopic-${self:custom.stage}
    WebsocketApiMapping: ${self:custom.dynamic.resources.apiMapping}
    LambdaEventSourceMappingMetricsTable: ${self:custom.dynamic.resources.metricsEventMap}
    LambdaEventSourceMappingContactsTable: ${self:custom.dynamic.resources.contactsEventMap}
    LambdaEventSourceMappingAgentsTable: ${self:custom.dynamic.resources.agentsEventMap}



