name: crisiscleanup-3-awsconnect

service: crisiscleanup-3-awsconnect
app: crisiscleanup-3-awsconnect
org: crisiscleanup

package:
  individually: true

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: '*'

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-plugin-warmup
  - serverless-dotenv-plugin
  - serverless-prune-plugin

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
    packager: 'yarn'
  warmup:
    enabled: true
    events:
      - schedule: rate(5 minutes)
    prewarm: true
    concurrency: 1
  prune:
    automatic: true
    number: 5

functions:
  awsConnect:
    handler: src/index.default

resources:
  Resources:
    # Connect Metrics Table
    metricsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: connect-metrics-table
        AttributeDefinitions:
          - AttributeName: type
            AttributeType: S
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: type
            KeyType: HASH
          - AttributeName: name
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    agentsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: connect-agents-table
        AttributeDefinitions:
          - AttributeName: agent_id
            AttributeType: S
          - AttributeName: state
            AttributeType: S
        KeySchema:
          - AttributeName: agent_id
            KeyType: HASH
          - AttributeName: state
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
