Resources:
  CCUConCluster:
    Type: AWS::DAX::Cluster
    Properties:
      ClusterName: ${self:custom.prefix}
      Description: Cluster CCU Connect
      IAMRoleARN: !GetAtt CCUConDaxRole.Arn
      NodeType: ${self:custom.dax.nodeType}
      ReplicationFactor: ${self:custom.dax.replicationFactor}
      SecurityGroupIds:
        - !GetAtt ProfileServiceSecurityGroup.GroupId
      SubnetGroupName: !Ref CCUConSubnetGroup

  CCUConDaxRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - dax.amazonaws.com
        Version: '2012-10-17'
      RoleName: ${self:custom.prefix}-dax-role
      Policies:
        - PolicyName: DAXAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Resource: '*'
                Action:
                  - 'dax:*'
                  - 'dynamodb:Query'
                  - 'dynamodb:Scan'
                  - 'dynamodb:UpdateItem'
                  - 'dynamodb:DeleteItem'
                  - 'dynamodb:PutItem'
                  - 'dynamodb:GetItem'
                  - 'dynamodb:BatchGetItem'
                  - 'dynamodb:DescribeTable'
                  - 'dynamodb:DescribeStream'
                  - 'dynamodb:BatchWriteItem'
                  - 'dynamodb:GetShardIterator'
                  - 'dynamodb:ListStreams'
                  - 'dynamodb:GetRecords'
                  - 'dynamodb:UpdateTimeToLive'
                  - 'dynamodb:ConditionCheckItem'
                  - 'dynamodb:DescribeTimeToLive'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
