name: CCU Connect

on:
  pull_request: ~
  push:
    branches:
      - master


jobs:
  test:
    runs-on: ubuntu-latest
    name: Tests

    steps:
      - uses: actions/checkout@v2

      - name: Run Tests
        run: docker-compose run tester


