name: CCU Connect

on:
  pull_request: ~
  push:
    branches:
      - master


jobs:
  test:
    runs-on: ubuntu-latest
    name: Tests

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn install

      - name: Run Tests
        run: |
          echo "" > .env
          echo "" > .env.dev
          echo "" > .env.staging
          echo "" > .env.prod
          docker-compose run tester


